live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 17

[font.normal]
family = "D2Coding Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 18
y = 16
