
[env]
TERM = "xterm-256color"

[font]
size = 17

[font.normal]
family = "D2Coding Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.65
blur = true
option_as_alt = "OnlyLeft"

[scrolling]
history = 100000
multiplier = 2

[window.padding]
x = 18
y = 16
